continuously try to config

diff --git a/helm-charts/submarine/templates/submarine-server.yaml b/helm-charts/submarine/templates/submarine-server.yaml
--- a/helm-charts/submarine/templates/submarine-server.yaml
+++ b/helm-charts/submarine/templates/submarine-server.yaml
@@ -57,11 +57,18 @@ spec:
       initContainers:
       - name: submarine-server-initcontainer
         image: "minio/mc"
-        command: ["sh", "-c", 
-        "if ! /bin/bash -c 'mc config host add minio http://submarine-minio-service:9000 
-        submarine_minio submarine_minio' 2>&1; then
-          exit 1;
-        fi;
+        command: ["/bin/bash", "-c", 
+        "cnt=0;
+        while ! /bin/bash -c 'mc config host add minio http://submarine-minio-service:9000 
+        submarine_minio submarine_minio' 2>&1; 
+        do
+          sleep 15;
+          ((cnt=cnt+1));
+          if [ $cnt -eq 80 ];then
+            echo 'ERROR: wait too long for minio pod';
+            exit 1;
+          fi;
+        done;
         if /bin/bash -c 'mc ls minio/submarine' >/dev/null 2>&1; then
           echo 'Bucket minio/submarine already exists, skipping creation.';
         else
