SUBMARINE-1025. Use minio client in init container to create bucket
### What is this PR for?
Migrate the minio logic to init container for submarine and mlflow pod. If the init container fails, let it restart.

### What type of PR is it?
Bug Fix

### Todos

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-1025

### How should this be tested?
Original e2e test.

### Screenshots (if appropriate)

### Questions:
* Do the license files need updating? No
* Are there breaking changes for older versions? No
* Does this need new documentation? No

Author: jeff-901 <b07901052@ntu.edu.tw>

Signed-off-by: Kevin <pingsutw@apache.org>

Closes #750 from jeff-901/SUBMARINE-1025 and squashes the following commits:

46ea9abc [jeff-901] continuously try to config
80585d03 [jeff-901] migrate create bucket to init container

diff --git a/helm-charts/submarine/templates/submarine-mlflow.yaml b/helm-charts/submarine/templates/submarine-mlflow.yaml
--- a/helm-charts/submarine/templates/submarine-mlflow.yaml
+++ b/helm-charts/submarine/templates/submarine-mlflow.yaml
@@ -62,6 +62,26 @@ spec:
       labels:
         app: submarine-mlflow-pod
     spec:
+      initContainers:
+      - name: submarine-mlflow-initcontainer
+        image: "minio/mc"
+        command: ["/bin/bash", "-c", 
+        "cnt=0;
+        while ! /bin/bash -c 'mc config host add minio http://submarine-minio-service:9000 
+        submarine_minio submarine_minio' 2>&1; 
+        do
+          sleep 15;
+          ((cnt=cnt+1));
+          if [ $cnt -eq 80 ];then
+            echo 'ERROR: wait too long for minio pod';
+            exit 1;
+          fi;
+        done;
+        if /bin/bash -c 'mc ls minio/mlflow' >/dev/null 2>&1; then
+          echo 'Bucket minio/mlflow already exists, skipping creation.';
+        else
+          /bin/bash -c 'mc mb minio/mlflow';
+        fi;"]
       containers:
       - name: submarine-mlflow-container
         image: apache/submarine:mlflow-0.6.0-SNAPSHOT
