Format according to yamllint

diff --git a/submarine-cloud-v2/artifacts/submarine/submarine-server.yaml b/submarine-cloud-v2/artifacts/submarine/submarine-server.yaml
--- a/submarine-cloud-v2/artifacts/submarine/submarine-server.yaml
+++ b/submarine-cloud-v2/artifacts/submarine/submarine-server.yaml
@@ -51,29 +51,30 @@ spec:
     metadata:
       labels:
         app: "submarine-server"
-      
     spec:
       serviceAccountName: "submarine-server"
       initContainers:
       - name: submarine-server-initcontainer
         image: "minio/mc"
-        command: ["/bin/bash", "-c", 
-        "cnt=0;
-        while ! /bin/bash -c 'mc config host add minio http://submarine-minio-service:9000 
-        submarine_minio submarine_minio' 2>&1; 
-        do
-          sleep 15;
-          ((cnt=cnt+1));
-          if [ $cnt -eq 80 ];then
-            echo 'ERROR: wait too long for minio pod';
-            exit 1;
-          fi;
-        done;
-        if /bin/bash -c 'mc ls minio/submarine' >/dev/null 2>&1; then
-          echo 'Bucket minio/submarine already exists, skipping creation.';
-        else
-          /bin/bash -c 'mc mb minio/submarine';
-        fi;"]
+        command: [
+          "/bin/bash", "-c",
+          "cnt=0;
+          while ! /bin/bash -c 'mc config host add minio http://submarine-minio-service:9000
+          submarine_minio submarine_minio' 2>&1;
+          do
+            sleep 15;
+            ((cnt=cnt+1));
+            if [ $cnt -eq 80 ];then
+              echo 'ERROR: wait too long for minio pod';
+              exit 1;
+            fi;
+          done;
+          if /bin/bash -c 'mc ls minio/submarine' >/dev/null 2>&1; then
+            echo 'Bucket minio/submarine already exists, skipping creation.';
+          else
+            /bin/bash -c 'mc mb minio/submarine';
+          fi;"
+        ]
       containers:
       - name: "submarine-server"
         env:
